config/routes.rb
Rails.application.routes.draw do
  resources :pins
  resources :pins
  devise_for :users
  root 'home#index'
get 'home/about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
    belongs_to :user
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100#" },
    :default_url => "/images/:style/missing.png",
    :url  => ":s3_domain_url",
    :storage => :fog,
    :fog_credentials => {
        provider: 'AWS',
        aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]
    },
    fog_directory: ENV["FOG_DIRECTORY"]
    validates_attachment_content_type :image, :content_type =>/\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
  def about
    
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin został pomyślnie utworzony.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin został pomyślnie zaktualizowany.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin został pomyślnie usunięty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Nie jesteś uprawniony do edycji tego pinu" if @pin.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-dark bg-dark">
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="/">Startowa</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/home/about">O mnie</a>
  </li>
  <li class="nav-item"><a class="nav-link" href="/pins/">Piny</a></li>
  <% if user_signed_in? %>
  <li class="nav-item"><a class="nav-link" href="/pins/new">Nowy pin</a></li>
  <li class="nav-item"><a class="nav-link" href="/users/edit">Profil</a></li>
  <li class="nav-item"><%=link_to"Wylogowanie", destroy_user_session_path, method: :delete%></li>
  <%else%>
  <li class="nav-item"><a class="nav-link" href="/users/sign_in">Zaloguj</a></li>
  <li class="nav-item"><a class="nav-link" href="/users/sign_up">Zarejestruj</a></li>
  <%end%>
</ul>

</nav>

app/views/home/about.html.erb
 <h1>O mnie</h1>
 <p>Nazywam się Jędrzej Sokołowski i programistą Ruby jestem od 6.10.2017 r. czyli wczoraj.</p>

app/views/home/index.html.erb
<h1>Witaj użytkowniku!</h1>
<p>Oto moja pierwsza apka :)</p>
<%=link_to 'Startowa', root_path, class: 'btn btn-primary'%>
<%=link_to 'O mnie', home_about_path, class: 'btn btn-primary'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Z książki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
<%=render 'home/header'%>
<div class="jumbotron">
<%flash.each do |name, msg|%>
<% content_tag(:div, msg, class:"alert alert-info")%>
<%end%>
<%= yield %>
</div>


</body>
</html>

app/views/pins/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body"><%= form_for @pin, html: {multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, "Opis" %><br>
    <%= f.text_field :description %>
  </div>
  <div class=form-group">
  <%= f.label :image, "Obraz"%>
  <%= f.file_field :image, class:"form-control"%>
  </div>
  <div class="actions">
     </div>
   <%= f.submit "Utwórz pin", class: 'btn btn-primary'%>
</div>
   
  </div>
<% end %>

app/views/pins/edit.html.erb
  <h1>Edycja Pinu</h1>
<div class="panel panel-default">
  <div class="panel-body">
<%= render 'form' %>
  </div>
  <div class="panel-footer"><%= link_to 'Pokaż', @pin , class: 'btn btn-primary'%> |
<%= link_to 'Wróć', pins_path, class: 'btn btn-primary' %></div>
</div>


    

app/views/pins/index.html.erb
<p id="notice"><%= notice%></p>

<h1>Lista pinów</h1>
<div class="panel panel-default">
  <div class="panel-body">
<table>
 
  <thead>
    <tr>
      <th>Obraz</th>
      <th>Opis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     
    <% @pins.each do |pin| %>
      <tr>
        <td> <%= image_tag pin.image.url(:medium)%></td>
        <td height="40"><%= pin.description %></td>
        </tr>
        <tr>
        <td width="100" height="20"><%= link_to 'Pokaż', pin, class: 'btn btn-primary' %></td>
        <% if pin.user==current_user %>
        <td width="100" height="20"><%= link_to 'Edytuj', edit_pin_path(pin), class: 'btn btn-primary' %></td>
        <td width="100" height="20"><%= link_to 'Usuń', pin, method: :delete, data: { confirm: 'Jesteś tego pewien?' }, class: 'btn btn-primary' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  </div>
  <div class="panel-footer"><%= link_to 'Nowy Pin', new_pin_path , class: 'btn btn-primary' %></div>
</div>

app/views/pins/new.html.erb
<h1>Nowy Pin</h1>
<div class="panel panel-default">
  <div class="panel-body">
<%= render 'form' %>
</div>
  <div class="panel-footer"><%= link_to 'Wróć', pins_path, class: 'btn btn-primary' %></div>
</div>



  

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <div class="panel panel-default">
  <div class="panel-body">
  <%=image_tag @pin.image.url(:medium)%><br/>
  <strong>Wpis:</strong>
  <%= @pin.description %>

</p>
 </div>
<% if @pin.user==current_user %>
  <div class="panel-footer"><%= link_to 'Edytuj', edit_pin_path(@pin), class: 'btn btn-primary' %>
  <% end %>
<%= link_to 'Wróć', pins_path, class: 'btn btn-primary' %></div>

</div>

 